instructions:
- type: general
  content: /
    Below is a conversation between a virtual assistant and a Ledger user.
  

models:
- type: main
  engine: openai
  model: text-davinci-003
  #model : gpt-3.5-turbo-0613
